//! Windows-only build step: embed the app icon and version metadata into `devterm.exe`.
//!
//! Without this the taskbar, Start Menu, desktop shortcut, and the file's Properties dialog
//! would all fall back to the generic executable icon. On non-Windows targets this is a
//! no-op. Icon regenerated by `scripts/make-icon.ps1`.

fn main() {
    // Only the MSVC/Windows targets carry an .rc resource; skip everywhere else.
    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() != Ok("windows") {
        return;
    }

    println!("cargo:rerun-if-changed=../../assets/devterm.ico");

    let mut res = winresource::WindowsResource::new();
    // Path is relative to this crate's manifest dir (where build.rs runs).
    res.set_icon("../../assets/devterm.ico");

    if let Err(e) = res.compile() {
        // Don't hard-fail local dev builds if the resource compiler is unavailable;
        // the binary still works, it just lacks the embedded icon.
        println!("cargo:warning=failed to embed Windows resources: {e}");
    }
}
